name: nexvpn_app
description: Nex - VPN клиент на Flutter с ядром Xray.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  flutter_v2ray: ^1.0.10          # ядро Xray + Android VpnService
  installed_apps: '>=1.4.0 <2.0.0' # список приложений для Per-App Routing
  android_intent_plus: ^5.0.0     # переход в системные настройки VPN (Kill Switch)
  device_info_plus: ^10.1.0       # модель и версия Android для заголовков HWID

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icon/nex_logo.png
